version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wishlist-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wishlist-server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/wishlist?authSource=admin
    volumes:
      - ./server:/usr/src/app

volumes:
  mongodb_data: